import type { Vehicle } from '@/types/vehicle';

export const seedVehicles: Vehicle[] = [
  {
    slug: 'mercedes-benz-eqe-suv-350',
    brand: 'Mercedes-Benz',
    model: 'EQE SUV',
    trim: '350',
    bodyType: 'suv',
    drivetrain: 'rwd',
    rangeKm: 590,
    rangeStandard: 'WLTP',
    batteryKwh: 96,
    dcChargeKw: 170,
    acChargeKw: 11,
    startingPriceEgp: 4_250_000,
    etaWeeks: 8,
    status: 'currently_advertising',
    isFeatured: true,
    featuredWeek: 18,
    heroImageUrl: '/images/seed/eqe-suv-hero.jpg',
    galleryImageUrls: [
      '/images/seed/eqe-suv-1.jpg',
      '/images/seed/eqe-suv-2.jpg',
      '/images/seed/eqe-suv-3.jpg',
    ],
    specs: [
      { label: 'Length', value: '4863 mm' },
      { label: 'Wheelbase', value: '3030 mm' },
      { label: 'Cargo', value: '520 / 1675 L' },
      { label: '0–100 km/h', value: '6.6 s' },
      { label: 'Top speed', value: '210 km/h' },
      { label: 'AC charging', value: '11 kW' },
    ],
    features: {
      adas: ['Level 2+ Driving Assist', 'Active Lane Keep', 'ACC w/ Stop&Go'],
      comfort: ['Air suspension', '4-zone climate', 'Heated/cooled massage front seats'],
      tech: ['Hyperscreen', '5G connectivity', 'OTA updates', '360° camera', 'Burmester sound'],
    },
    countryOfOrigin: 'CN',
    deliveryBranch: 'EG',
  },
  {
    slug: 'byd-song-l-awd',
    brand: 'BYD',
    model: 'Song L',
    trim: 'AWD',
    bodyType: 'suv',
    drivetrain: 'awd',
    rangeKm: 602,
    rangeStandard: 'CLTC',
    batteryKwh: 80,
    dcChargeKw: 150,
    acChargeKw: 11,
    startingPriceEgp: 1_400_000,
    etaWeeks: 6,
    status: 'currently_advertising',
    isFeatured: true,
    featuredWeek: 18,
    heroImageUrl: '/images/seed/song-l-hero.jpg',
    galleryImageUrls: ['/images/seed/song-l-1.jpg', '/images/seed/song-l-2.jpg'],
    specs: [
      { label: 'Length', value: '4840 mm' },
      { label: 'Wheelbase', value: '2930 mm' },
      { label: '0–100 km/h', value: '4.3 s' },
      { label: 'Top speed', value: '190 km/h' },
    ],
    features: {
      adas: ['Level 2 ADAS', 'Adaptive cruise', 'Lane keep'],
      comfort: ['Dual-zone climate', 'Heated front seats', 'Power tailgate'],
      tech: ['15.6" rotating screen', 'DiPilot', 'Wireless CarPlay & Auto', '12-speaker audio'],
    },
    countryOfOrigin: 'CN',
    deliveryBranch: 'EG',
  },
  {
    slug: 'nevo-q05-long-range',
    brand: 'NEVO',
    model: 'Q05',
    trim: 'Long Range',
    bodyType: 'suv',
    drivetrain: 'fwd',
    rangeKm: 520,
    rangeStandard: 'CLTC',
    batteryKwh: 65,
    dcChargeKw: 100,
    acChargeKw: 11,
    startingPriceEgp: 1_100_000,
    etaWeeks: 6,
    status: 'currently_advertising',
    isFeatured: true,
    featuredWeek: 18,
    heroImageUrl: '/images/seed/q05-hero.jpg',
    galleryImageUrls: ['/images/seed/q05-1.jpg', '/images/seed/q05-2.jpg'],
    specs: [
      { label: 'Length', value: '4720 mm' },
      { label: 'Wheelbase', value: '2820 mm' },
      { label: '0–100 km/h', value: '7.8 s' },
    ],
    features: {
      adas: ['Lane departure warning', 'Automatic emergency braking'],
      comfort: ['Climate control', 'Heated front seats'],
      tech: ['12.3" infotainment', 'Wireless charging pad'],
    },
    countryOfOrigin: 'CN',
    deliveryBranch: 'EG',
  },
  {
    slug: 'bmw-ix3-m-sport',
    brand: 'BMW',
    model: 'iX3',
    trim: 'M Sport',
    bodyType: 'suv',
    drivetrain: 'rwd',
    rangeKm: 460,
    rangeStandard: 'WLTP',
    batteryKwh: 80,
    dcChargeKw: 150,
    acChargeKw: 11,
    startingPriceEgp: 3_800_000,
    etaWeeks: 8,
    status: 'currently_advertising',
    isFeatured: true,
    featuredWeek: 18,
    heroImageUrl: '/images/seed/ix3-hero.jpg',
    galleryImageUrls: ['/images/seed/ix3-1.jpg'],
    specs: [
      { label: 'Length', value: '4734 mm' },
      { label: '0–100 km/h', value: '6.8 s' },
      { label: 'Top speed', value: '180 km/h' },
    ],
    features: {
      adas: ['Driving Assistant Professional', 'ACC', 'Lane Change Assistant'],
      comfort: ['Vernasca leather', 'Sport seats', 'Panoramic roof'],
      tech: ['BMW iDrive 8.5', 'Curved display', 'Harman Kardon'],
    },
    countryOfOrigin: 'CN',
    deliveryBranch: 'EG',
  },
  {
    slug: 'denza-d9-premium',
    brand: 'Denza',
    model: 'D9',
    trim: 'Premium',
    bodyType: 'mpv',
    drivetrain: 'fwd',
    rangeKm: 600,
    rangeStandard: 'CLTC',
    batteryKwh: 103,
    dcChargeKw: 166,
    acChargeKw: 11,
    startingPriceEgp: 2_600_000,
    etaWeeks: 7,
    status: 'recently_delivered',
    isFeatured: false,
    heroImageUrl: '/images/seed/d9-hero.jpg',
    galleryImageUrls: [],
    specs: [
      { label: 'Length', value: '5250 mm' },
      { label: 'Wheelbase', value: '3110 mm' },
      { label: 'Seating', value: '7' },
    ],
    features: {
      adas: ['Driving assist', 'Surround view'],
      comfort: ['Captain chairs row 2', 'Refrigerator', 'Reclining lounger seats'],
      tech: ['DiLink 5.0', 'Rear entertainment screens'],
    },
    countryOfOrigin: 'CN',
    deliveryBranch: 'EG',
  },
  {
    slug: 'honda-enp2',
    brand: 'Honda',
    model: 'e:NP2',
    bodyType: 'suv',
    drivetrain: 'fwd',
    rangeKm: 510,
    rangeStandard: 'CLTC',
    batteryKwh: 68,
    dcChargeKw: 90,
    acChargeKw: 7,
    startingPriceEgp: 1_300_000,
    etaWeeks: 8,
    status: 'catalog_only',
    isFeatured: false,
    heroImageUrl: '/images/seed/enp2-hero.jpg',
    galleryImageUrls: [],
    specs: [
      { label: 'Length', value: '4505 mm' },
      { label: '0–100 km/h', value: '7.6 s' },
    ],
    features: {
      adas: ['Honda Sensing 360'],
      comfort: ['Auto climate', 'Heated front seats'],
      tech: ['15.1" central display', 'Honda Connect'],
    },
    countryOfOrigin: 'CN',
    deliveryBranch: 'EG',
  },
];
